### ISSUE TITLE
PHP_CodeSniffer v3.0

### ISSUE THREAD

**Issue by o5** [Moxio/php-codesniffer-sniffs#1]
Hello,

could you merge branch [phpcs-3.0](https://github.com/Moxio/php-codesniffer-sniffs/tree/phpcs-3.0) to master? I just check it with phpcs `3.0.1` and it works fine.

Thanks
Peter

**Comment by aboks** [comment]
I have just released version 1.0.0, which is compatible with PHP_CodeSniffer version 3.x (and does not support the 2.x-branch anymore). Thanks for testing the sniffs with the stable phpcs 3.x release!
